[workspace]
resolver = "2"
members = ["common", "tp1", "tp2", "tp3", "tp4", "tp5", "tp6", "tp8", "tp9"]

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
plotters = "0.3"
blue_engine = "0.6"
