[package]
name = "tp9-subdivision-triangle"
version = "0.1.0"
edition = "2024"

[dependencies]
geonum-common = { path = "../common", features = ["3d"] }
blue_engine = { workspace = true }
clap = { workspace = true }

