[package]
name = "tp6-bezier-surface"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
blue_engine = { workspace = true }
geonum-common = { path = "../common", features = ["3d"] }
tp1-bezier = { path = "../tp1" }
